# Configuracion necesaria para conectarse a la base de dato de MYSQL
spring.application.name=rh
spring.datasource.url=jdbc:mysql://localhost:3306/recuros_humanos_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Para que se cree la bd automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true